# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'proventaapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for proventaapp

  target 'proventaapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'react-native-maps', :path => '../node_modules/react-native-maps'

    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

    pod 'react-native-calendar-events', :path => '../node_modules/react-native-calendar-events'

  end

  target 'proventaappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  react_native_path = "../node_modules/react-native"
  pod "yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod "React", :path => react_native_path
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
 
  pod 'GoogleMaps'



end

target 'proventaapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for proventaapp-tvOS

  # target 'proventaapp-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
