# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'proventaapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for proventaapp

  target 'proventaapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  end

  target 'proventaappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  react_native_path = "../node_modules/react-native"
  pod "yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod "React", :path => react_native_path
               
 
  pod 'GoogleMaps'

end

target 'proventaapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for proventaapp-tvOS

  # target 'proventaapp-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
